# Generated by Django 3.2.12 on 2025-08-13 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_navigationlink'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_title', models.CharField(default='Contact Us', max_length=200)),
                ('page_title_bn', models.CharField(blank=True, help_text='Bengali page title', max_length=200)),
                ('page_subtitle', models.CharField(default='Get in touch with us for any inquiries or information', max_length=300)),
                ('page_subtitle_bn', models.CharField(blank=True, help_text='Bengali page subtitle', max_length=300)),
                ('address', models.TextField(help_text='Full address of the school')),
                ('address_bn', models.TextField(blank=True, help_text='Bengali address')),
                ('main_phone', models.CharField(help_text='Main office phone number', max_length=50)),
                ('admissions_phone', models.CharField(blank=True, help_text='Admissions phone number', max_length=50)),
                ('additional_phone', models.CharField(blank=True, help_text='Additional phone number', max_length=50)),
                ('general_email', models.EmailField(help_text='General contact email', max_length=254)),
                ('admissions_email', models.EmailField(blank=True, help_text='Admissions email', max_length=254)),
                ('office_hours', models.TextField(help_text='Office hours information')),
                ('office_hours_bn', models.TextField(blank=True, help_text='Bengali office hours')),
                ('map_embed_code', models.TextField(blank=True, help_text='Google Maps embed code (iframe)')),
                ('latitude', models.DecimalField(blank=True, decimal_places=8, help_text='Latitude for map', max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=8, help_text='Longitude for map', max_digits=11, null=True)),
                ('enable_contact_form', models.BooleanField(default=True, help_text='Enable contact form on the page')),
                ('form_title', models.CharField(default='Send us a Message', max_length=200)),
                ('form_title_bn', models.CharField(blank=True, help_text='Bengali form title', max_length=200)),
                ('additional_info', models.TextField(blank=True, help_text='Any additional contact information')),
                ('additional_info_bn', models.TextField(blank=True, help_text='Bengali additional information')),
                ('is_active', models.BooleanField(default=True, help_text='Use this contact information')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Contact Information',
                'verbose_name_plural': 'Contact Information',
                'ordering': ['-is_active', '-updated_date'],
            },
        ),
    ]
