# Generated by Django 3.2.12 on 2025-08-24 08:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0007_contactinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Student's full name", max_length=100)),
                ('roll_number', models.CharField(help_text='Student roll number', max_length=20)),
                ('class_name', models.CharField(choices=[('6', 'Class 6'), ('7', 'Class 7'), ('8', 'Class 8'), ('9', 'Class 9'), ('10', 'Class 10')], help_text="Student's class", max_length=10)),
                ('section', models.CharField(choices=[('A', 'Section A'), ('B', 'Section B'), ('C', 'Section C')], default='A', help_text="Student's section", max_length=5)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], help_text="Student's gender", max_length=10)),
                ('admission_date', models.DateField(help_text='Date of admission')),
                ('photo', models.ImageField(blank=True, help_text="Student's photo (optional)", null=True, upload_to='students/')),
                ('father_name', models.CharField(blank=True, help_text="Father's name", max_length=100)),
                ('mother_name', models.CharField(blank=True, help_text="Mother's name", max_length=100)),
                ('guardian_phone', models.CharField(blank=True, help_text="Guardian's phone number", max_length=20)),
                ('address', models.TextField(blank=True, help_text="Student's address")),
                ('is_active', models.BooleanField(default=True, help_text='Is currently enrolled')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
                'ordering': ['class_name', 'section', 'roll_number'],
                'unique_together': {('roll_number', 'class_name', 'section')},
            },
        ),
        migrations.CreateModel(
            name='HomepageSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Slide title', max_length=200)),
                ('subtitle', models.CharField(blank=True, help_text='Slide subtitle (optional)', max_length=300)),
                ('image', models.ImageField(help_text='Slider image (recommended: 1920x800px)', upload_to='slider/')),
                ('caption', models.TextField(blank=True, help_text='Image caption or description')),
                ('link_url', models.URLField(blank=True, help_text='Optional link URL when slide is clicked')),
                ('link_text', models.CharField(blank=True, help_text='Link button text', max_length=100)),
                ('open_new_tab', models.BooleanField(default=False, help_text='Open link in new tab')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (lower numbers first)')),
                ('is_active', models.BooleanField(default=True, help_text='Show this slide')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Homepage Slider',
                'verbose_name_plural': 'Homepage Sliders',
                'ordering': ['order', '-created_date'],
            },
        ),
        migrations.CreateModel(
            name='ExamResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="Result title (e.g., 'First Term Exam 2024')", max_length=200)),
                ('class_name', models.CharField(choices=[('6', 'Class 6'), ('7', 'Class 7'), ('8', 'Class 8'), ('9', 'Class 9'), ('10', 'Class 10')], help_text='Class for this result', max_length=10)),
                ('exam_type', models.CharField(choices=[('first_term', 'First Term'), ('second_term', 'Second Term'), ('final', 'Final Exam'), ('test', 'Test Exam'), ('annual', 'Annual Exam')], help_text='Type of examination', max_length=20)),
                ('result_type', models.CharField(choices=[('pdf', 'PDF File'), ('image', 'Image File')], default='pdf', help_text='Choose file type for result', max_length=10)),
                ('result_file', models.FileField(blank=True, help_text='Upload PDF or image file', null=True, upload_to='exam_results/')),
                ('exam_date', models.DateField(help_text='Date when exam was conducted')),
                ('result_publish_date', models.DateField(help_text='Date when result was published')),
                ('description', models.TextField(blank=True, help_text='Additional information about the exam')),
                ('is_published', models.BooleanField(default=False, help_text='Make result visible to public')),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Exam Result',
                'verbose_name_plural': 'Exam Results',
                'ordering': ['-result_publish_date', 'class_name', 'exam_type'],
            },
        ),
    ]
