# Generated by Django 3.2.12 on 2025-08-24 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_examresult_homepageslider_student'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homepageslider',
            options={'ordering': ['order'], 'verbose_name': 'Homepage Slider', 'verbose_name_plural': 'Homepage Sliders'},
        ),
        migrations.RemoveField(
            model_name='homepageslider',
            name='caption',
        ),
        migrations.RemoveField(
            model_name='homepageslider',
            name='link_text',
        ),
        migrations.RemoveField(
            model_name='homepageslider',
            name='link_url',
        ),
        migrations.RemoveField(
            model_name='homepageslider',
            name='open_new_tab',
        ),
        migrations.RemoveField(
            model_name='homepageslider',
            name='subtitle',
        ),
        migrations.RemoveField(
            model_name='homepageslider',
            name='title',
        ),
        migrations.RemoveField(
            model_name='homepageslider',
            name='updated_date',
        ),
        migrations.RemoveField(
            model_name='student',
            name='address',
        ),
        migrations.RemoveField(
            model_name='student',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='student',
            name='father_name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='guardian_phone',
        ),
        migrations.RemoveField(
            model_name='student',
            name='mother_name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='student',
            name='updated_date',
        ),
        migrations.AddField(
            model_name='examresult',
            name='text_content',
            field=models.TextField(blank=True, help_text='Enter result content if using text format', null=True),
        ),
        migrations.AlterField(
            model_name='examresult',
            name='result_type',
            field=models.CharField(choices=[('pdf', 'PDF File'), ('image', 'Image File'), ('text', 'Text Content')], default='pdf', help_text='Choose file type for result', max_length=10),
        ),
    ]
