# Generated by Django 3.2.12 on 2025-08-24 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20250824_0951'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Name of the exam type (e.g., 'First Term')", max_length=50)),
                ('code', models.CharField(help_text="Short code for the exam type (e.g., 'first_term')", max_length=20, unique=True)),
                ('description', models.TextField(blank=True, help_text='Description of this exam type')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order in lists')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this exam type is currently in use')),
            ],
            options={
                'verbose_name': 'Exam Type',
                'verbose_name_plural': 'Exam Types',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='StudentClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Class name (e.g., 'Class 6')", max_length=50)),
                ('code', models.CharField(help_text="Short code for the class (e.g., '6')", max_length=10, unique=True)),
                ('description', models.TextField(blank=True, help_text='Description of this class')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order in lists')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this class is currently accepting students')),
            ],
            options={
                'verbose_name': 'Student Class',
                'verbose_name_plural': 'Student Classes',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AlterModelOptions(
            name='examresult',
            options={'ordering': ['-result_publish_date', 'student_class', 'exam_type'], 'verbose_name': 'Exam Result', 'verbose_name_plural': 'Exam Results'},
        ),
        migrations.RemoveField(
            model_name='examresult',
            name='class_name',
        ),
        migrations.AddField(
            model_name='examresult',
            name='student_class',
            field=models.ForeignKey(help_text='Class for this result', null=True, on_delete=django.db.models.deletion.PROTECT, to='main.studentclass'),
        ),
        migrations.AlterField(
            model_name='examresult',
            name='exam_type',
            field=models.ForeignKey(help_text='Type of examination', null=True, on_delete=django.db.models.deletion.PROTECT, to='main.examtype'),
        ),
    ]
