# Generated by Django 3.2.12 on 2025-08-24 10:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0010_auto_20250824_1008'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClasswiseStudentCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.PositiveIntegerField(help_text='Academic year (e.g., 2025)')),
                ('total_students', models.PositiveIntegerField(help_text='Total number of students in this class')),
                ('total_male', models.PositiveIntegerField(default=0, help_text='Number of male students')),
                ('total_female', models.PositiveIntegerField(default=0, help_text='Number of female students')),
                ('section_a_count', models.PositiveIntegerField(default=0, help_text='Number of students in Section A')),
                ('section_b_count', models.PositiveIntegerField(default=0, help_text='Number of students in Section B')),
                ('section_c_count', models.PositiveIntegerField(default=0, help_text='Number of students in Section C')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('student_class', models.ForeignKey(help_text='Class for which to record student count', on_delete=django.db.models.deletion.PROTECT, to='main.studentclass')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Class-wise Student Count',
                'verbose_name_plural': 'Class-wise Student Counts',
                'ordering': ['academic_year', 'student_class__order'],
                'unique_together': {('student_class', 'academic_year')},
            },
        ),
    ]
