# Generated by Django 3.2.12 on 2025-08-24 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_clean_exam_results'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classwisestudentcount',
            name='section_a_count',
        ),
        migrations.RemoveField(
            model_name='classwisestudentcount',
            name='section_b_count',
        ),
        migrations.RemoveField(
            model_name='classwisestudentcount',
            name='section_c_count',
        ),
    ]
