# Generated by Django 3.2.12 on 2025-08-24 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_examresult_fields'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.AlterField(
            model_name='homepageslider',
            name='image',
            field=models.ImageField(help_text='Slider image (recommended: 800x400px)', upload_to='slider/'),
        ),
    ]
