# Generated by Django 3.2.12 on 2025-08-26 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_merge'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtherEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('designation', models.CharField(help_text='e.g., Cleaner, Guard, Office Assistant', max_length=100)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='other_employee/')),
                ('contact_info', models.CharField(blank=True, max_length=200)),
                ('bio', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Other Employee',
                'verbose_name_plural': 'Other Employees',
                'ordering': ['name'],
            },
        ),
    ]
